In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
# Importing data set
df = pd.read_csv("50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
len(df)

50

In [5]:
# Splitting the data into X and y 
X =df.iloc[:, :-1].values

y = df.iloc[:, -1].values

In [6]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [7]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [8]:
X.shape, y.shape

((50, 4), (50,))

In [9]:
type(X), type(y)

(numpy.ndarray, numpy.ndarray)

In [10]:
# incoding the cotegorical data

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer



In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [12]:

transformer = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder="passthrough")
X = transformer.fit_transform(X)
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [13]:
X[:,3:]

array([[165349.2, 136897.8, 471784.1],
       [162597.7, 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34, 91391.77, 366168.42],
       [131876.9, 99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96, 91790.61, 249744.55],
       [93863.75, 127320.38, 249839.44],
       [91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [78013.11, 121597.55, 264346.06],
       [94657.16, 145077.58, 282574.31],
       [91749.16, 114175.79, 294919.57],
       [86419.7, 153514.11, 0.0],
       [76253.86, 113867.3, 298664.47],
       [78389.47, 153773.43, 299737.29],
       [73994.56, 122782.75, 303319.26],
       [67532.53, 105751.03, 304768.73],
       [77044.01, 

In [14]:
X.shape

(50, 6)

In [15]:
X[0]

array([0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [17]:
# fitting Multiple Linear Rgression to the training set 

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [18]:
# Predicting the test set result 
y_pred = regressor.predict(X_test)

In [19]:
regressor.score(X_test, y_test)

0.9347068473282795

In [20]:
y_pred

array([103015.20159796, 132582.27760816, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230165,  67851.69209675,  98791.73374687,
       113969.43533013, 167921.06569552])

In [21]:

y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [22]:
len(X_train), len(y_train)

(40, 40)

In [23]:
len(X_train), len(regressor.predict(X_train))

(40, 40)

In [24]:
# Let's try Standard Scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [25]:
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [26]:
X_train

array([[0.0, 1.0, 0.0, -0.3500645436227844, -0.7854710924793271,
        0.1011968019362538],
       [0.0, 0.0, 1.0, -0.555303187426314, -1.481174262628151,
        0.02734979174277092],
       [0.0, 1.0, 0.0, 0.07935762307586282, 0.8013338146656704,
        -0.551521323997471],
       [1.0, 0.0, 0.0, -0.5463823849331263, 1.3250581707161837,
        0.07011683779235604],
       [0.0, 1.0, 0.0, 0.4348537132854595, -0.3559866348200946,
        0.7514851578736048],
       [0.0, 1.0, 0.0, 1.2694314288195354, 0.855185185174973,
        0.986031184474382],
       [0.0, 1.0, 0.0, 1.045250070905001, 1.2807704710942711,
        0.44039999942558483],
       [0.0, 0.0, 1.0, -1.529843000700978, 0.029420649133439825,
        -1.6218751012780783],
       [0.0, 0.0, 1.0, -1.5397625087372082, -2.767672641730695,
        -1.6372965026688253],
       [0.0, 0.0, 1.0, -0.13115188245559178, 1.144977005989267,
        -0.7694999122824163],
       [0.0, 0.0, 1.0, 0.927916133722245, -0.029920619212990152,
   

In [27]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

In [28]:
regressor.fit(X_train, y_train)

LinearRegression()

In [29]:
# Predicting the test set result 
y_pred = regressor.predict(X_test)

In [30]:
regressor.score(X_test, y_test)

0.9347068473282424